export interface MakeSeed {
  make: string;
  model: ModelSeed[];
}

export interface ModelSeed {
  item: string;
}

export const allMakeSeed: MakeSeed[] = [
  {
    make: "Acura",
    model: [
      { item: "MDX" },
      { item: "RDX" },
      { item: "TLX" },
      { item: "ILX" },
      { item: "TL" },
      { item: "TSX" },
      { item: "RLX" },
      { item: "RL" },
      { item: "NSX" },
      { item: "RSX" },
      { item: "CL" },
      { item: "TSX Sport Wagon" },
      { item: "Integra" },
      { item: "ZDX" },
      { item: "Legend" },
      { item: "ILX Hybrid" },
      { item: "SLX" }
    ]
  },
  {
    make: "Alfa Romeo",
    model: [
      { item: "Giulia" },
      { item: "Stelvio" },
      { item: "4C" },
      { item: "Spider" },
      { item: "164" },
      { item: "8C" },
      { item: "8C Competizione Spider" },
      { item: "Gtv-6" }
    ]
  },
  {
    make: "AMC",
    model: [
      { item: "CJ7" },
      { item: "Eagle" },
      { item: "Grand Wagoneer" },
      { item: "Spirit" },
      { item: "Wrangler" }
    ]
  },
  { make: "AM General", model: [{ item: "Hummer" }, { item: "Mv-1" }] },
  {
    make: "Aston Martin",
    model: [
      { item: "V8 Vantage" },
      { item: "DB11" },
      { item: "DB9" },
      { item: "DBS" },
      { item: "Vanquish" },
      { item: "Rapide S" },
      { item: "V12 Vantage S" },
      { item: "Vanquish S" },
      { item: "V12 Vanquish" },
      { item: "Rapide" },
      { item: "DB7" },
      { item: "V12 Vantage" },
      { item: "Virage" },
      { item: "DB9 GT" },
      { item: "Vanquish Zagato" },
      { item: "DB7 Vantage" },
      { item: "V8" }
    ]
  },
  {
    make: "Audi",
    model: [
      { item: "Q7" },
      { item: "Q5" },
      { item: "A4" },
      { item: "A6" },
      { item: "A5" },
      { item: "A3" },
      { item: "Q8" },
      { item: "SQ5" },
      { item: "A7" },
      { item: "S5" },
      { item: "A8" },
      { item: "Q3" },
      { item: "S4" },
      { item: "RS 5" },
      { item: "TT" },
      { item: "S3" },
      { item: "R8" },
      { item: "RS5" },
      { item: "Allroad" },
      { item: "S6" },
      { item: "TTS" },
      { item: "S7" },
      { item: "A3 Sportback E-tron" },
      { item: "RS 7" },
      { item: "S8" },
      { item: "A4 Allroad" },
      { item: "allroad quattro" },
      { item: "RS 4" },
      { item: "TT RS" },
      { item: "RS 6" },
      { item: "RS 3" },
      { item: "Cabriolet" },
      { item: "RS7" },
      { item: "4000" },
      { item: "5000" },
      { item: "5000 Wagon" },
      { item: "A6 Avant" }
    ]
  },
  {
    make: "Bentley",
    model: [
      { item: "Continental GT" },
      { item: "Continental GTC" },
      { item: "Bentayga" },
      { item: "Flying Spur" },
      { item: "Continental Flying Spur" },
      { item: "Mulsanne" },
      { item: "Continental" },
      { item: "Continental GT Speed" },
      { item: "Continental Flying Spur Speed" },
      { item: "Continental GTC Speed" },
      { item: "Arnage" },
      { item: "Continental GT Speed Convertible" },
      { item: "Azure" },
      { item: "Continental Supersports" },
      { item: "Continental Supersports Convertible" },
      { item: "Brooklands" },
      { item: "Continental GT3-R" },
      { item: "Azure T" },
      { item: "Turbo" },
      { item: "Supersports Convertible ISR" },
      { item: "Turbo R" }
    ]
  },
  {
    make: "BMW",
    model: [
      { item: "3 Series" },
      { item: "X3" },
      { item: "X5" },
      { item: "5 Series" },
      { item: "X1" },
      { item: "4 Series" },
      { item: "7 Series" },
      { item: "540i" },
      { item: "530i" },
      { item: "X2" },
      { item: "M3" },
      { item: "X6" },
      { item: "i3" },
      { item: "330i" },
      { item: "4 Series Gran Coupe" },
      { item: "530e" },
      { item: "2 Series" },
      { item: "X4" },
      { item: "M4" },
      { item: "M5" },
      { item: "4-Series Gran Coupe" },
      { item: "6 Series" },
      { item: "440i" },
      { item: "X7" },
      { item: "i8" },
      { item: "Z4" },
      { item: "1 Series" },
      { item: "4-Series" },
      { item: "6 Series Gran Coupe" },
      { item: "3 Series Gran Turismo" },
      { item: "M240i" },
      { item: "230i" },
      { item: "M550i" },
      { item: "3-Series" },
      { item: "640xi" },
      { item: "M6" },
      { item: "M" },
      { item: "M850i" },
      { item: "X5 M" },
      { item: "M2" },
      { item: "740i" },
      { item: "5 Series Gran Turismo" },
      { item: "X5 eDrive" },
      { item: "Z3" },
      { item: "X6 M" },
      { item: "6 Series Gran Turismo" },
      { item: "7-Series" },
      { item: "320i" },
      { item: "M6 Gran Coupe" },
      { item: "5-Series" },
      { item: "Z8" },
      { item: "Z4 M" },
      { item: "M760i" },
      { item: "740e" },
      { item: "8 Series" },
      { item: "M4 GTS" },
      { item: "6-Series" },
      { item: "1-Series" },
      { item: "540d" },
      { item: "640i" },
      { item: "650i" },
      { item: "750i" },
      { item: "3 Series eDrive" },
      { item: "R1200GS" },
      { item: "ActiveHybrid 7" },
      { item: "K03" },
      { item: "S1000RR" },
      { item: "R1200RT" },
      { item: "340i" },
      { item: "ActiveHybrid X6" },
      { item: "K1200LT" },
      { item: "R1150rt" },
      { item: "Rninet" },
      { item: "ActiveHybrid 5" },
      { item: "650i / B6" },
      { item: "G650gs" },
      { item: "K1200GT" },
      { item: "K1200S" },
      { item: "R1200R" },
      { item: "C650gt" },
      { item: "F800R" },
      { item: "R1200gs Adventure" },
      { item: "F800GS" },
      { item: "F800st" },
      { item: "K 1" },
      { item: "K33" },
      { item: "K47" },
      { item: "R1100RT" },
      { item: "R1200cl" },
      { item: "328d" },
      { item: "633CSi" },
      { item: "C600" },
      { item: "F650gs" },
      { item: "HP4" },
      { item: "K 1600 GT" },
      { item: "K02" },
      { item: "K1100rs" },
      { item: "K1200RS" },
      { item: "K1200r Sport" },
      { item: "K1300gt" },
      { item: "K1600" },
      { item: "K1600 B" },
      { item: "K22" },
      { item: "K32" },
      { item: "R 100 GS" },
      { item: "R 100 RT" },
      { item: "R1100s" },
      { item: "R1150gs" },
      { item: "R1150r" },
      { item: "R1200rs" },
      { item: "S1000xr" }
    ]
  },
  {
    make: "Bugatti",
    model: [
      { item: "Veyron W16.4" },
      { item: "Chiron" },
      { item: "Veyron" },
      { item: "Veyron 16.4" }
    ]
  },
  {
    make: "Buick",
    model: [
      { item: "Encore" },
      { item: "Enclave" },
      { item: "Envision" },
      { item: "LaCrosse" },
      { item: "Regal Tourx" },
      { item: "Regal" },
      { item: "Verano" },
      { item: "Regal Sportback" },
      { item: "Lucerne" },
      { item: "Cascada" },
      { item: "LeSabre" },
      { item: "Rendezvous" },
      { item: "Century" },
      { item: "Park Avenue" },
      { item: "Rainier" },
      { item: "Terraza" },
      { item: "Riviera" },
      { item: "Reatta" },
      { item: "Roadmaster" },
      { item: "Allure" },
      { item: "Skylark" },
      { item: "Century Wagon" }
    ]
  },
  {
    make: "Cadillac",
    model: [
      { item: "XT5" },
      { item: "Escalade" },
      { item: "XT4" },
      { item: "CTS" },
      { item: "Escalade ESV" },
      { item: "XTS" },
      { item: "SRX" },
      { item: "ATS" },
      { item: "CT6" },
      { item: "DTS" },
      { item: "Deville" },
      { item: "ATS Coupe" },
      { item: "CTS Coupe" },
      { item: "STS" },
      { item: "Escalade EXT" },
      { item: "CTS-V" },
      { item: "ATS-V" },
      { item: "Seville" },
      { item: "Stretch Limousine" },
      { item: "Eldorado" },
      { item: "Funeral Coach" },
      { item: "CTS-V Coupe" },
      { item: "ELR" },
      { item: "XLR" },
      { item: "CTS Wagon" },
      { item: "Allante" },
      { item: "Escalade Hybrid" },
      { item: "Fleetwood" },
      { item: "Krystal Koach" },
      { item: "Brougham" },
      { item: "STS-V" },
      { item: "CTS-V Wagon" },
      { item: "Catera" },
      { item: "XLR-V" },
      { item: "Hearse" },
      { item: "S&S" },
      { item: "Deville/Fleetwood" },
      { item: "Limousine" },
      { item: "SLS" }
    ]
  },
  {
    make: "Chevrolet",
    model: [
      { item: "Equinox" },
      { item: "Silverado" },
      { item: "Silverado 1500" },
      { item: "Cruze" },
      { item: "Malibu" },
      { item: "Traverse" },
      { item: "Colorado" },
      { item: "Tahoe" },
      { item: "Trax" },
      { item: "Silverado HD" },
      { item: "Camaro" },
      { item: "Impala" },
      { item: "Suburban" },
      { item: "Corvette" },
      { item: "Silverado 2500HD" },
      { item: "Spark" },
      { item: "Express" },
      { item: "Sonic" },
      { item: "Blazer" },
      { item: "Bolt EV" },
      { item: "Volt" },
      { item: "Silverado " },
      { item: "Silverado 3500HD" },
      { item: "Avalanche" },
      { item: "Cruze Limited" },
      { item: "TrailBlazer" },
      { item: "Express Cargo" },
      { item: "Silverado Legacy" },
      { item: "Cobalt" },
      { item: "Malibu Limited" },
      { item: "Impala Limited" },
      { item: "HHR" },
      { item: "Captiva Sport" },
      { item: "Silverado LD" },
      { item: "3500 / 4500" },
      { item: "Aveo" },
      { item: "Silverado 1500 Classic" },
      { item: "Corvette Stingray" },
      { item: "Monte Carlo" },
      { item: "C/K 1500" },
      { item: "Black Diamond Avalanche" },
      { item: "Uplander" },
      { item: "Cavalier" },
      { item: "Silverado 3500" },
      { item: "TrailBlazer EXT" },
      { item: "S-10" },
      { item: "City Express" },
      { item: "Silverado 2500HD Classic" },
      { item: "S10 Pickup" },
      { item: "Express 3500" },
      { item: "Venture" },
      { item: "Malibu Maxx" },
      { item: "Spark EV" },
      { item: "SSR" },
      { item: "SS" },
      { item: "Silverado 1500HD" },
      { item: "C/K 3500" },
      { item: "Silverado 2500" },
      { item: "Astro" },
      { item: "4500 HD" },
      { item: "C/K 2500" },
      { item: "4502 HD" },
      { item: "4500xd" },
      { item: "Tracker" },
      { item: "Express Cutaway" },
      { item: "5500xd" },
      { item: "Lumina" },
      { item: "Silverado 1500 Hybrid" },
      { item: "Tahoe Hybrid" },
      { item: "C/K 10" },
      { item: "Astro Cargo" },
      { item: "5500hd" },
      { item: "Classic" },
      { item: "Silverado 3500HD CC" },
      { item: "Malibu Classic" },
      { item: "P30" },
      { item: "Prizm" },
      { item: "Silverado 3500 Classic" },
      { item: "Caprice Classic" },
      { item: "Caprice" },
      { item: "C4500" },
      { item: "4501 HD" },
      { item: "C/K 1500 Series" },
      { item: "El Camino" },
      { item: "Sport Van" },
      { item: "Bolt Incomplete" },
      { item: "Impala SS" },
      { item: "C4C042" },
      { item: "C4E042" },
      { item: "C5C042" },
      { item: "G-Series Van" },
      { item: "Chevy Van" },
      { item: "Silverado Classic 3500" },
      { item: "S10 Blazer" },
      { item: "Tahoe Limited/Z71" },
      { item: "W45042" },
      { item: "6500XD" },
      { item: "Malibu Hybrid" },
      { item: "S10" },
      { item: "C7H042" },
      { item: "C6H042" },
      { item: "C7C042" },
      { item: "4500" },
      { item: "Metro" },
      { item: "R10" },
      { item: "C/K 10 Blazer" },
      { item: "C/K 20" },
      { item: "Corsica" },
      { item: "Silverado 1500HD Classic" },
      { item: "4499 HD" },
      { item: "C5500" },
      { item: "C5V042" },
      { item: "Explorer" },
      { item: "Express 2500" },
      { item: "V10" },
      { item: "3500hd" },
      { item: "C5U042" },
      { item: "C5e042" },
      { item: "Express Passenger" },
      { item: "K1500" },
      { item: "LCF" },
      { item: "V10 Blazer" },
      { item: "2500 EXTENDED CAB" },
      { item: "4503 HD" },
      { item: "C6C042" },
      { item: "W35042" },
      { item: "W55042" },
      { item: "3500 SILVERADO REG C" },
      { item: "C/K 30" },
      { item: "C6500" },
      { item: "Conversion Van" },
      { item: "Silverado Classic 2500HD" },
      { item: "W4s042" },
      { item: "Beretta" },
      { item: "C/K 2500 Series" },
      { item: "C/K 3500 Series" },
      { item: "Express Commercial Cutaway" },
      { item: "Kodiak" },
      { item: "Lumina Minivan" },
      { item: "R30" },
      { item: "S TRUCK" },
      { item: "C4V042" },
      { item: "C7H064" },
      { item: "C8" },
      { item: "Caprice Police Vehicle" },
      { item: "D30" },
      { item: "Express 1500" },
      { item: "G1500 Vans" },
      { item: "R20" },
      { item: "V10 Suburban" },
      { item: "Venture Passenger" },
      { item: "1500" },
      { item: "C/K 20 Suburban" },
      { item: "C/K2500" },
      { item: "C8c042" },
      { item: "Caprice Classic Wagon" },
      { item: "Caprice Wagon" },
      { item: "Celebrity" },
      { item: "Chassis Stripped" },
      { item: "Commercial Vans" },
      { item: "Express 4500" },
      { item: "Express Van G3500" },
      { item: "F6b042" },
      { item: "G3500" },
      { item: "Nova" },
      { item: "R10 Suburban" },
      { item: "S-10 Blazer" },
      { item: "Suburban 1500" },
      { item: "V20" },
      { item: "V30" },
      { item: "3500 Regular Cab" },
      { item: "4500 Kodiak" },
      { item: "Aveo5" },
      { item: "B7t042" },
      { item: "C/K 10 Suburban" },
      { item: "C/K1500" },
      { item: "C3500" },
      { item: "C4c044" },
      { item: "C6d042" },
      { item: "C7D042" },
      { item: "C7e042" },
      { item: "CK2500" },
      { item: "C\\/K 1500" },
      { item: "Chevette" },
      { item: "Chevy Van Classic" },
      { item: "Express Van G2500" },
      { item: "G30 VAN" },
      { item: "G3500 VAN" },
      { item: "GMT-400" },
      { item: "MOTOR HOME" },
      { item: "Malibu Classic Wagon" },
      { item: "Pickup" },
      { item: "R20 Suburban" },
      { item: "S10 Extended Cab" },
      { item: "S10 LS" },
      { item: "SILVERADO 4WD" },
      { item: "Van" },
      { item: "Wt5500" }
    ]
  },
  {
    make: "Chrysler",
    model: [
      { item: "Pacifica" },
      { item: "300" },
      { item: "200" },
      { item: "Town and Country" },
      { item: "Pacifica Hybrid" },
      { item: "PT Cruiser" },
      { item: "Sebring" },
      { item: "Aspen" },
      { item: "Crossfire" },
      { item: "300M" },
      { item: "Town & Country" },
      { item: "Concorde" },
      { item: "Voyager" },
      { item: "LHS" },
      { item: "Prowler" },
      { item: "Cirrus" },
      { item: "Le Baron" },
      { item: "TC" },
      { item: "LeBaron" },
      { item: "Fifth Avenue" },
      { item: "New Yorker" },
      { item: "TC By Maserati" },
      { item: "Cordoba" },
      { item: "Grand Voyager" },
      { item: "Imperial" },
      { item: "Intrepid" }
    ]
  },
  {
    make: "Daewoo",
    model: [{ item: "Leganza" }, { item: "Nubira" }, { item: "Lanos" }]
  },
  { make: "Datsun", model: [{ item: "280ZX" }, { item: "300ZX" }] },
  {
    make: "Dodge",
    model: [
      { item: "Journey" },
      { item: "Charger" },
      { item: "Durango" },
      { item: "Challenger" },
      { item: "Grand Caravan" },
      { item: "Caravan/Grand Caravan" },
      { item: "Ram Pickup 1500" },
      { item: "Dart" },
      { item: "Ram Pickup 2500" },
      { item: "Avenger" },
      { item: "Dakota" },
      { item: "Ram Pickup 3500" },
      { item: "Ram 1500" },
      { item: "Caliber" },
      { item: "Nitro" },
      { item: "Caravan" },
      { item: "Stratus" },
      { item: "Viper" },
      { item: "Magnum" },
      { item: "Ram 3500" },
      { item: "Neon" },
      { item: "Ram 2500" },
      { item: "Intrepid" },
      { item: "Sprinter Cargo" },
      { item: "Ram Van" },
      { item: "Ram 5500" },
      { item: "SRT Viper" },
      { item: "Ram 4500" },
      { item: "Ram Wagon" },
      { item: "Sprinter Van" },
      { item: "Stealth" },
      { item: "Sprinter" },
      { item: "Ram Cargo" },
      { item: "Ram" },
      { item: "Ramcharger" },
      { item: "Ram 1500 Club Cab" },
      { item: "W150" },
      { item: "D150" },
      { item: "Spirit" },
      { item: "W250" },
      { item: "Ram 150" },
      { item: "Ram 250" },
      { item: "Sprinter Wagon" },
      { item: "D350" },
      { item: "Dakota Regular Cab" },
      { item: "Omni" },
      { item: "Ram 350" },
      { item: "Ram 50" },
      { item: "Daytona" },
      { item: "Ram 1500 Regular Cab" },
      { item: "Spinter Chassis Cab" },
      { item: "grand carvan" },
      { item: "400" },
      { item: "D250" },
      { item: "DAKOTA EXTENDED CAB" },
      { item: "Dynasty" },
      { item: "Pleasure Way" },
      { item: "RAM WAGON 3500" },
      { item: "Ram 2500 Club Cab" },
      { item: "Rampage" },
      { item: "Shadow" },
      { item: "600" },
      { item: "Aries" },
      { item: "D50" },
      { item: "Mini RAM" },
      { item: "Ram 2500 Regular Cab" },
      { item: "Shelby Charger" },
      { item: "W350" }
    ]
  },
  {
    make: "Eagle",
    model: [{ item: "Vision" }, { item: "Talon" }, { item: "Summit" }]
  },
  {
    make: "Ferrari",
    model: [
      { item: "458 Italia" },
      { item: "California" },
      { item: "F430" },
      { item: "California T" },
      { item: "488 GTB" },
      { item: "F12 Berlinetta" },
      { item: "360" },
      { item: "599" },
      { item: "488 Spider" },
      { item: "488 Gts" },
      { item: "FF" },
      { item: "GTC4Lusso" },
      { item: "430 Scuderia" },
      { item: "F355" },
      { item: "488" },
      { item: "612 Scaglietti" },
      { item: "Testarossa" },
      { item: "575M" },
      { item: "360 Modena" },
      { item: "328" },
      { item: "348" },
      { item: "F12 Special Series" },
      { item: "458 Speciale A" },
      { item: "550 Maranello" },
      { item: "308" },
      { item: "Superamerica" },
      { item: "512 TR" },
      { item: "LA Ferrari" },
      { item: "Mondial" },
      { item: "456M" },
      { item: "550" },
      { item: "360 Challenge" },
      { item: "456" },
      { item: "portofino" },
      { item: "Enzo" },
      { item: "F40" },
      { item: "F512m" },
      { item: "348 TS" },
      { item: "599 GTB Fiorano" },
      { item: "F430 Coupe" }
    ]
  },
  {
    make: "FIAT",
    model: [
      { item: "500" },
      { item: "500X" },
      { item: "124 Spider" },
      { item: "500L" },
      { item: "500e" },
      { item: "Pininfarina" },
      { item: "Spider 124" }
    ]
  },
  { make: "Fisker", model: [{ item: "Karma" }] },
  {
    make: "Ford",
    model: [
      { item: "F-150" },
      { item: "Escape" },
      { item: "Explorer" },
      { item: "Fusion" },
      { item: "Edge" },
      { item: "Mustang" },
      { item: "F-250" },
      { item: "EcoSport" },
      { item: "Focus" },
      { item: "Expedition" },
      { item: "Fiesta" },
      { item: "Transit Connect" },
      { item: "F-250 Super Duty" },
      { item: "F-350" },
      { item: "Transit" },
      { item: "Taurus" },
      { item: "Ranger" },
      { item: "F-350 Super Duty" },
      { item: "Flex" },
      { item: "Transit Van" },
      { item: "F-550" },
      { item: "Fusion Hybrid" },
      { item: "Expedition MAX" },
      { item: "Transit Wagon" },
      { item: "F-450" },
      { item: "F-350 SD" },
      { item: "F-250 SD" },
      { item: "E-Series Van" },
      { item: "Econoline" },
      { item: "Fusion Energi" },
      { item: "E-350" },
      { item: "Explorer Sport Trac" },
      { item: "C-Max Energi" },
      { item: "F-750" },
      { item: "F-650" },
      { item: "C-Max Hybrid" },
      { item: "Econoline Cargo" },
      { item: "F-450 SD" },
      { item: "Shelby GT350" },
      { item: "Focus ST" },
      { item: "Thunderbird" },
      { item: "Crown Victoria" },
      { item: "Excursion" },
      { item: "E-Series Wagon" },
      { item: "Shelby GT500" },
      { item: "Econoline Wagon" },
      { item: "Expedition EL" },
      { item: "E-450" },
      { item: "Five Hundred" },
      { item: "F-450 Super Duty" },
      { item: "Freestar" },
      { item: "Windstar" },
      { item: "Motorhome Chassis" },
      { item: "Freestyle" },
      { item: "Transit-350" },
      { item: "Escape Hybrid" },
      { item: "E-350SD" },
      { item: "Commercial Chassis" },
      { item: "Focus RS" },
      { item: "Escort" },
      { item: "Stripped Chassis Motorhome" },
      { item: "F-150 Heritage" },
      { item: "Taurus X" },
      { item: "Explorer Sport" },
      { item: "GT" },
      { item: "Bronco" },
      { item: "Mustang SVT Cobra" },
      { item: "Stripped Chassis" },
      { item: "F-550SD" },
      { item: "Club Wagon" },
      { item: "Contour" },
      { item: "E-Series Chassis" },
      { item: "F-530" },
      { item: "E-450SD" },
      { item: "F-150 SVT Lightning" },
      { item: "Utility Police Interceptor" },
      { item: "Super Duty F-350 DRW" },
      { item: "F350" },
      { item: "Aerostar" },
      { item: "F800" },
      { item: "Sedan Police Interceptor" },
      { item: "Probe" },
      { item: "F700" },
      { item: "E-150" },
      { item: "F150" },
      { item: "Transit Chassis Cab" },
      { item: "Bronco II" },
      { item: "F Series" },
      { item: " Super Duty F-250" },
      { item: "E-250" },
      { item: "F-450SD" },
      { item: "E350" },
      { item: "F700f" },
      { item: "LCF 450" },
      { item: "Windstar Cargo" },
      { item: "Escort Wagon" },
      { item: "F450 SUPER DUTY REG" },
      { item: "Super Duty F-250" },
      { item: "F250 4x4 Crew Cab Hunting Truck" },
      { item: "F450" },
      { item: "F650" },
      { item: "F800f" },
      { item: "LCF 550" },
      { item: "E450" },
      { item: "Focus Wagon" },
      { item: "Tempo" },
      { item: "F-250SD" },
      { item: "F250" },
      { item: "F550" },
      { item: "FSD" },
      { item: "MUSTANG GT" },
      { item: "Transit Cutaway" },
      { item: "Cf7000" },
      { item: "F-100" },
      { item: "F-250 4 X 4" },
      { item: "F-250 SUPER" },
      { item: "F450 Super Duty Regular Cab & Chassis" },
      { item: "F650 XL" },
      { item: "F800 LPO" },
      { item: "LTD Crown Victoria" },
      { item: "Taurus Wagon" },
      { item: "Windstar Passenger" },
      { item: "14 Passenger VAN" },
      { item: "Cf8000" },
      { item: "Commercial Vans" },
      { item: "E150 Super Duty Passenger" },
      { item: "F-450 SUPER DUTY XL 4X4" },
      { item: "F-550 Super Duty" },
      { item: "F250hd XL 4x4 5.8l" },
      { item: "F350 SUPER DUTY REG" },
      { item: "F7000" },
      { item: "Festiva" },
      { item: "Ln8000f" },
      { item: "MH Stripped Chassis" },
      { item: "MH Stripped Chssis" },
      { item: "Motorhome" },
      { item: "Think" },
      { item: "35C" },
      { item: "Aspire" },
      { item: "B800" },
      { item: "C-Max" },
      { item: "Crown Victoria Wagon" },
      { item: "Custom" },
      { item: "E" },
      { item: "E150" },
      { item: "Econoline Commercial Chassis" },
      { item: "F150 REG CAB 4x4" },
      { item: "F250 Regular Cab" },
      { item: "F250 SUPER DUTY REG" },
      { item: "F350 Super Duty Super Cab & Chassis" },
      { item: "F590f" },
      { item: "F600f" },
      { item: "F700 LPO" },
      { item: "F750" },
      { item: "F8000" },
      { item: "Fairmont" },
      { item: "L8000" },
      { item: "LN8000" },
      { item: "Lnt8000f" },
      { item: "Ls8000f" },
      { item: "Ls9000" },
      { item: "Ltla9000" },
      { item: "Ranger Regular Cab" },
      { item: "Sterling" }
    ]
  },
  {
    make: "Geo",
    model: [
      { item: "Prizm" },
      { item: "Tracker" },
      { item: "Metro" },
      { item: "Storm" }
    ]
  },
  {
    make: "GMC",
    model: [
      { item: "Acadia" },
      { item: "Sierra" },
      { item: "Sierra 1500" },
      { item: "Terrain" },
      { item: "Yukon" },
      { item: "Yukon XL" },
      { item: "Canyon" },
      { item: "Sierra 2500HD" },
      { item: "Sierra HD" },
      { item: "Savana" },
      { item: "Sierra 3500HD" },
      { item: "Savana Cargo" },
      { item: "Envoy" },
      { item: "Acadia Limited" },
      { item: "Sierra Limited" },
      { item: "Envoy XL" },
      { item: "Sonoma" },
      { item: "Sierra 1500 Classic" },
      { item: "Sierra C/K 1500" },
      { item: "Sierra 2500HD Classic" },
      { item: "Sierra 3500" },
      { item: "Savana 2500" },
      { item: "Jimmy" },
      { item: "Suburban" },
      { item: "Yukon Hybrid" },
      { item: "Safari" },
      { item: "Envoy XUV" },
      { item: "Savana G3500" },
      { item: "Sierra 1500HD" },
      { item: "Sierra 2500" },
      { item: "C5C042" },
      { item: "Sierra C/K 3500" },
      { item: "C7H042" },
      { item: "C7C042" },
      { item: "W45042" },
      { item: "Sierra C/K 2500" },
      { item: "Sierra Classic 3500" },
      { item: "Sierra 1500 Hybrid" },
      { item: "C4C042" },
      { item: "C6C042" },
      { item: "C4E042" },
      { item: "Sierra 3500 Classic" },
      { item: "C6H042" },
      { item: "Yukon Denali" },
      { item: "P3500" },
      { item: "C/K 1500" },
      { item: "Sierra Classic 1500" },
      { item: "Vandura" },
      { item: "Safari Cargo" },
      { item: "Sierra 1500HD Classic" },
      { item: "W35042" },
      { item: "Typhoon" },
      { item: "B7t042" },
      { item: "C7d042" },
      { item: "C8c042" },
      { item: "Sierra Classic 2500" },
      { item: "C/K 2500" },
      { item: "C7500" },
      { item: "Conversion Van" },
      { item: "F7B042" },
      { item: "G-Series Van" },
      { item: "TopKick" },
      { item: "1500 Club Coupe" },
      { item: "C6500" },
      { item: "W5500-Hd" },
      { item: "C5500" },
      { item: "C5e042" },
      { item: "C5v042" },
      { item: "C8c064" },
      { item: "Caballero" },
      { item: "F6b042" },
      { item: "S15 Pickup" },
      { item: "C/K 3500" },
      { item: "C4c044" },
      { item: "Rally" },
      { item: "Sierra C3" },
      { item: "V1500" },
      { item: "W55042" },
      { item: "1500" },
      { item: "C/K 1500 Suburban" },
      { item: "C7" },
      { item: "Jimmy S15" },
      { item: "R3500" },
      { item: "S15 Jimmy" },
      { item: "Safari Passenger" },
      { item: "Savana G4500" },
      { item: "Savana VAN" },
      { item: "Sierra (Classic) 3500 Regular Cab" },
      { item: "Sierra Classic 2500HD" },
      { item: "Sierra K1500" },
      { item: "Syclone" },
      { item: "TOPKICK C4500 6.6 DURAMAX" },
      { item: "W4S042" },
      { item: "C-SERIES" },
      { item: "C/K2500 Classic" },
      { item: "C4/C5/C6/c7/c8" },
      { item: "C4500" },
      { item: "C5D042" },
      { item: "C8" },
      { item: "Commercial Vans" },
      { item: "F8b064" },
      { item: "Jimmy Utility" },
      { item: "P6s042" },
      { item: "R1500" },
      { item: "R1500 Suburban" },
      { item: "Rally Wagon" },
      { item: "Savana Cutaway" },
      { item: "Sierra 1500 Regular Cab" },
      { item: "T7500" },
      { item: "W" },
      { item: "WT5500" }
    ]
  },
  {
    make: "Honda",
    model: [
      { item: "Civic" },
      { item: "Accord" },
      { item: "CR-V" },
      { item: "Pilot" },
      { item: "Odyssey" },
      { item: "HR-V" },
      { item: "Ridgeline" },
      { item: "Insight" },
      { item: "Fit" },
      { item: "Passport" },
      { item: "Passport UV" },
      { item: "Clarity" },
      { item: "Element" },
      { item: "Accord Hybrid" },
      { item: "Crosstour" },
      { item: "CR-Z" },
      { item: "Accord Crosstour" },
      { item: "S2000" },
      { item: "Prelude" },
      { item: "Civic del Sol" },
      { item: "CBR600RR" },
      { item: "GL1800" },
      { item: "VTX1300C" },
      { item: "CBR1000RR" },
      { item: "Accord Plug-In Hybrid" },
      { item: "VT750C" },
      { item: "VT1100C" },
      { item: "CBR250R/RA" },
      { item: "CMX250C" },
      { item: "GL1500SE" },
      { item: "VT1100C2" },
      { item: "VT750C2F" },
      { item: "VT600CD" },
      { item: "CBR300R" },
      { item: "Cb250" },
      { item: "VT750C2" },
      { item: "VT750CA" },
      { item: "VT1300CS" },
      { item: "CBR500R" },
      { item: "NC700X" },
      { item: "VT750DC" },
      { item: "VTX1300R" },
      { item: "GL1500A" },
      { item: "VFR1300CR" },
      { item: "VT750C2B" },
      { item: "Crf450r" },
      { item: "Shadow" },
      { item: "VTX1300S" },
      { item: "VTX1800S" },
      { item: "CBR650F" },
      { item: "Crf1000a" },
      { item: "VT1300CX" },
      { item: "CB500X" },
      { item: "VFR1300CT" },
      { item: "Vt750cda" },
      { item: "CBR900RR" },
      { item: "Cb1100" },
      { item: "Grom 125" },
      { item: "St1300" },
      { item: "VT750CDD" },
      { item: "VTX1800C" },
      { item: "CBR600" },
      { item: "CN250" },
      { item: "Cb500f" },
      { item: "Cmx300/Rebel300" },
      { item: "Ctx700nd-Ctx700n DCT" },
      { item: "FSC600A" },
      { item: "GL1100I" },
      { item: "GL1200" },
      { item: "Msx125/Grom" },
      { item: "Ruckus" },
      { item: "SH150D" },
      { item: "Sxs1000m3p/Pioneer 1000-3" },
      { item: "Trx250ex" },
      { item: "Trx350te" },
      { item: "Trx500fm2/Four Trax Foreman" },
      { item: "VT750CD" },
      { item: "VTX1300T" },
      { item: "Vf1100c" },
      { item: "Vfr800" },
      { item: "500fm" },
      { item: "CBR600F4" },
      { item: "CRF250L" },
      { item: "CRF250R" },
      { item: "CTX700" },
      { item: "Cb700sc" },
      { item: "Cbr500ra/Cbr500r" },
      { item: "Civic CRX" },
      { item: "Cmx500/Rebel500" },
      { item: "Ctx1300" },
      { item: "Ctx700n" },
      { item: "Gl1800a" },
      { item: "Gl1800bd/Gold Wing F6B" },
      { item: "Goldwing" },
      { item: "NPS50-RUKUS" },
      { item: "Nps50/Ruckus" },
      { item: "Nss250" },
      { item: "PCX150" },
      { item: "PSC600D" },
      { item: "TRX420FE" },
      { item: "TRX500FM" },
      { item: "TRX500FMC" },
      { item: "Trx250te" },
      { item: "Trx350tm" },
      { item: "Trx400ex" },
      { item: "Trx400te" },
      { item: "Trx420fm1/Four Trax Rancher" },
      { item: "Trx450es" },
      { item: "Trx500fa5/Four Trax Foreman" },
      { item: "Trx500fm1/Four Trax Foreman" },
      { item: "Trx90ex" },
      { item: "VF750C" },
      { item: "VT750" },
      { item: "VT750CD2" },
      { item: "VTX1800T2" },
      { item: "Vfr800f/Interceptor" },
      { item: "Vt1300cx-Fury" },
      { item: "Vtx1800n" },
      { item: "Vtx1800n2" },
      { item: "Accord LX" },
      { item: "CB300F" },
      { item: "CHF50" },
      { item: "CR 300" },
      { item: "CRF230F" },
      { item: "Cb1000r" },
      { item: "Cb750" },
      { item: "Cbr300r-Cbr300r" },
      { item: "Cbr650fa/Cbr650f" },
      { item: "Cmx300a/Rebel300" },
      { item: "Crf110f" },
      { item: "Crf150rb" },
      { item: "Crf250l/Rl" },
      { item: "Ct110" },
      { item: "Ctx1300d/Ctx1300" },
      { item: "Ctx700-Ctx700d" },
      { item: "Fury" },
      { item: "GL1500C" },
      { item: "GL1500CF" },
      { item: "Gl12sei" },
      { item: "Gl1500cd" },
      { item: "Gl1500ct" },
      { item: "Metropolitan" },
      { item: "Msx125a /Grom ABS" },
      { item: "Nch50/Metropolitan" },
      { item: "Ncw50/Metropolitan" },
      { item: "Nps50 - Ruckus" },
      { item: "Nrx1800ea" },
      { item: "Nss250a" },
      { item: "Nss300a/Forza" },
      { item: "ST1300A" },
      { item: "Sabre" },
      { item: "St1100" },
      { item: "Sxs1000m5d/Pioneer 1000-5" },
      { item: "Sxs700/Pioneer 700-4" },
      { item: "TRX420FA1/Four Trax Rancher" },
      { item: "TRX420FPM" },
      { item: "TRX450ER" },
      { item: "TRX500FPA" },
      { item: "TRX500FPM" },
      { item: "Trx250" },
      { item: "Trx250tm/Four Trax Recon" },
      { item: "Trx300" },
      { item: "Trx300ex" },
      { item: "Trx400tm" },
      { item: "Trx420fa" },
      { item: "Trx420fa5/Four Trax Rancher" },
      { item: "Trx420fe1/Four Trax Rancher" },
      { item: "Trx500fa" },
      { item: "Trx500fe/Four Trax Foreman" },
      { item: "Trx500fe1/Four Trax Foreman" },
      { item: "Trx500fm6" },
      { item: "Trx500fpe/Four Trax Foreman" },
      { item: "Trx650fa" },
      { item: "Trx680fa" },
      { item: "Trx700xx" },
      { item: "Trx90" },
      { item: "Trx90/Sportrax90" },
      { item: "VT1100C3" },
      { item: "VT600C" },
      { item: "VT750CDC" },
      { item: "VT750S" },
      { item: "VTX" },
      { item: "VTX1800C3" },
      { item: "VTX1800F2" },
      { item: "VTX1800N1" },
      { item: "VTX1800R" },
      { item: "Vf750c2" },
      { item: "Vfr1200xd" },
      { item: "Vt1300cxa" },
      { item: "Vt1300cxa/Fury" },
      { item: "Vt700c" },
      { item: "Vt750cdb" },
      { item: "Vt750cl-Shadow Aero" },
      { item: "Vtr1000 Sp-2" },
      { item: "Vtx1800c2" },
      { item: "Vtx1800f3" },
      { item: "Ww125ex2" },
      { item: "XR650L" },
      { item: "Xr400r" }
    ]
  },
  {
    make: "HUMMER",
    model: [
      { item: "H3" },
      { item: "H2" },
      { item: "H2 SUT" },
      { item: "H3T" },
      { item: "H1" },
      { item: "H1 Alpha" },
      { item: "Kscs" }
    ]
  },
  {
    make: "Hyundai",
    model: [
      { item: "Elantra" },
      { item: "Sonata" },
      { item: "Santa Fe" },
      { item: "Tucson" },
      { item: "Accent" },
      { item: "Santa Fe Sport" },
      { item: "Kona" },
      { item: "Ioniq Electric (Ev), Hybrid (Hev, Phev)" },
      { item: "Veloster" },
      { item: "Santa FE XL" },
      { item: "Elantra GT" },
      { item: "Genesis" },
      { item: "Sonata Hybrid" },
      { item: "Genesis Coupe" },
      { item: "Azera" },
      { item: "Ioniq Hybrid" },
      { item: "Veracruz" },
      { item: "Equus" },
      { item: "Elantra Touring" },
      { item: "Tiburon" },
      { item: "Elantra Coupe" },
      { item: "Entourage" },
      { item: "XG350" },
      { item: "Sonata Plug-In Hybrid" },
      { item: "Ioniq Electric" },
      { item: "Ioniq Plug-In Hybrid" },
      { item: "XG300" },
      { item: "Excel" },
      { item: "HUD 150" },
      { item: "Ld15a" },
      { item: "Nexo" }
    ]
  },
  {
    make: "INFINITI",
    model: [
      { item: "QX60" },
      { item: "Q50" },
      { item: "QX80" },
      { item: "QX50" },
      { item: "QX30" },
      { item: "Q70" },
      { item: "Q60" },
      { item: "G35" },
      { item: "G Sedan" },
      { item: "QX70" },
      { item: "QX56" },
      { item: "FX35" },
      { item: "G37" },
      { item: "Q60 Coupe" },
      { item: "QX" },
      { item: "M35" },
      { item: "JX" },
      { item: "Q70L" },
      { item: "M" },
      { item: "G Coupe" },
      { item: "Q40" },
      { item: "FX" },
      { item: "EX35" },
      { item: "G37 Sedan" },
      { item: "G Convertible" },
      { item: "M37" },
      { item: "EX" },
      { item: "Q60 Convertible" },
      { item: "I35" },
      { item: "G37 Coupe" },
      { item: "M45" },
      { item: "I30" },
      { item: "QX4" },
      { item: "G37 Convertible" },
      { item: "Q45" },
      { item: "FX45" },
      { item: "G20" },
      { item: "FX50" },
      { item: "M56" },
      { item: "J30" },
      { item: "Altima" },
      { item: "M30" }
    ]
  },
  {
    make: "Isuzu",
    model: [
      { item: "NPR" },
      { item: "NPR/ NPR-HD/ NPR-XD" },
      { item: "Rodeo" },
      { item: "NQR" },
      { item: "NQR/NRR" },
      { item: "Ascender" },
      { item: "Trooper" },
      { item: "i-Series" },
      { item: "FTR" },
      { item: "Npr/Npr-Hd" },
      { item: "Axiom" },
      { item: "Rodeo Sport" },
      { item: "Amigo" },
      { item: "4000 Series Medium Duty" },
      { item: "Hombre" },
      { item: "VehiCROSS" },
      { item: "FRR" },
      { item: "Truck" },
      { item: "5000 Series Medium Duty" },
      { item: "Pickup" },
      { item: "Oasis" },
      { item: "Trooper II" }
    ]
  },
  {
    make: "Jaguar",
    model: [
      { item: "F-Pace" },
      { item: "E-Pace" },
      { item: "XE" },
      { item: "XF" },
      { item: "XJ" },
      { item: "F-Type" },
      { item: "I-Pace" },
      { item: "XK" },
      { item: "S-Type" },
      { item: "X-Type" },
      { item: "XK8" },
      { item: "XJS" },
      { item: "XJ Sedan" },
      { item: "XJ6" },
      { item: "XJR" },
      { item: "XKR" },
      { item: "Xj12" }
    ]
  },
  {
    make: "Jeep",
    model: [
      { item: "Wrangler" },
      { item: "Grand Cherokee" },
      { item: "Cherokee" },
      { item: "Compass" },
      { item: "Renegade" },
      { item: "Wrangler JK" },
      { item: "Patriot" },
      { item: "Liberty" },
      { item: "Commander" },
      { item: "Grand Cherokee SRT" },
      { item: "Grand Wagoneer" },
      { item: "CJ-7" },
      { item: "Comanche" },
      { item: "Wrangler Laredo Fully Custom" }
    ]
  },
  {
    make: "KIA",
    model: [
      { item: "Sorento" },
      { item: "Optima" },
      { item: "Forte" },
      { item: "Soul" },
      { item: "Sportage" },
      { item: "Niro" },
      { item: "Sedona" },
      { item: "Rio" },
      { item: "Stinger" },
      { item: "Cadenza" },
      { item: "Telluride" },
      { item: "Optima Hybrid" },
      { item: "Spectra" },
      { item: "K900" },
      { item: "SUV" },
      { item: "Optima Hybrid/Plug-In Hybrid" },
      { item: "Rondo" },
      { item: "Telluram" },
      { item: "Amanti" },
      { item: "Soul EV" },
      { item: "Borrego" },
      { item: "Optima Plug-In Hybrid" },
      { item: "Sephia" },
      { item: "Soul, Soul EV" },
      { item: "Forte Koup" }
    ]
  },
  {
    make: "Lamborghini",
    model: [
      { item: "Huracan" },
      { item: "Gallardo" },
      { item: "Aventador" },
      { item: "Murcielago" },
      { item: "Hurracan" },
      { item: "Urus" },
      { item: "Diablo" },
      { item: "Countach" },
      { item: "Murcielago Lp640" }
    ]
  },
  {
    make: "Land Rover",
    model: [
      { item: "Range Rover Sport" },
      { item: "Range Rover" },
      { item: "Discovery Sport" },
      { item: "Range Rover Velar" },
      { item: "Range Rover Evoque" },
      { item: "Discovery" },
      { item: "LR4" },
      { item: "LR2" },
      { item: "LR3" },
      { item: "Defender" },
      { item: "Defender 90" },
      { item: "Discovery Series II" },
      { item: "Freelander" }
    ]
  },
  {
    make: "Lexus",
    model: [
      { item: "RX" },
      { item: "RX 350" },
      { item: "ES" },
      { item: "ES 350" },
      { item: "NX" },
      { item: "GX" },
      { item: "UX" },
      { item: "IS" },
      { item: "IS 250" },
      { item: "GS 350" },
      { item: "NX 200t" },
      { item: "GX 460" },
      { item: "LS 460" },
      { item: "GX, LX" },
      { item: "IS 200t" },
      { item: "CT 200h" },
      { item: "LS" },
      { item: "GS" },
      { item: "IS 350" },
      { item: "IS 300" },
      { item: "RC" },
      { item: "ES 300h" },
      { item: "RX 450h" },
      { item: "RC 350" },
      { item: "RX 330" },
      { item: "GX 470" },
      { item: "LX 570" },
      { item: "LS 500" },
      { item: "RX 350L" },
      { item: "ES 330" },
      { item: "NX 300" },
      { item: "LS 430" },
      { item: "ES 300" },
      { item: "RX 300" },
      { item: "SC 430" },
      { item: "RX 400h" },
      { item: "RC F" },
      { item: "GS 300" },
      { item: "IS 250 C" },
      { item: "LC" },
      { item: "LC 500" },
      { item: "RC 200t" },
      { item: "NX 300h" },
      { item: "RC 300" },
      { item: "LX 470" },
      { item: "HS 250h" },
      { item: "IS 350 C" },
      { item: "LS 400" },
      { item: "GS 200t" },
      { item: "GS F" },
      { item: "GS 450h" },
      { item: "IS F" },
      { item: "GS 430" },
      { item: "GS 300/400" },
      { item: "LS 600h L" },
      { item: "SC 300" },
      { item: "LC 500h" },
      { item: "LS 500h" },
      { item: "GS 460" },
      { item: "GS 400" },
      { item: "SC 400" },
      { item: "LX 450" },
      { item: "SC 300/400" },
      { item: "GS 400 Luxury Perform Sdn" },
      { item: "LFA" },
      { item: "ES 250" },
      { item: "HS" },
      { item: "SC" }
    ]
  },
  {
    make: "Lincoln",
    model: [
      { item: "MKZ" },
      { item: "MKC" },
      { item: "MKX" },
      { item: "Navigator" },
      { item: "Nautilus" },
      { item: "Continental" },
      { item: "MKS" },
      { item: "MKT" },
      { item: "Town Car" },
      { item: "LS" },
      { item: "Mark LT" },
      { item: "Aviator" },
      { item: "Zephyr" },
      { item: "Navigator L" },
      { item: "MKZ Hybrid" },
      { item: "Blackwood" },
      { item: "Mark VIII" },
      { item: "Mark VII" },
      { item: "Mark VI" },
      { item: "MKT Town Car" }
    ]
  },
  {
    make: "Lotus",
    model: [
      { item: "Evora" },
      { item: "Evora 400" },
      { item: "Elise" },
      { item: "Esprit" },
      { item: "Exige" },
      { item: "Elan" }
    ]
  },
  {
    make: "Maserati",
    model: [
      { item: "Ghibli" },
      { item: "Levante" },
      { item: "Quattroporte" },
      { item: "GranTurismo" },
      { item: "GranTurismo Convertible" },
      { item: "Spyder" },
      { item: "Coupe" },
      { item: "GranSport" },
      { item: "430" },
      { item: "Biturbo" }
    ]
  },
  { make: "Maybach", model: [{ item: "57" }, { item: "62" }] },
  {
    make: "Mazda",
    model: [
      { item: "CX-5" },
      { item: "3" },
      { item: "CX-9" },
      { item: "Mazda6" },
      { item: "CX-3" },
      { item: "6" },
      { item: "Mx-5" },
      { item: "MX-5 Miata" },
      { item: "CX-7" },
      { item: "5" },
      { item: "Tribute" },
      { item: "2" },
      { item: "MX-5 Miata RF" },
      { item: "RX-8" },
      { item: "Mazdaspeed 3" },
      { item: "MPV" },
      { item: "Protege" },
      { item: "626" },
      { item: "B-Series" },
      { item: "Mazdaspeed3" },
      { item: "B-Series Truck" },
      { item: "RX-7" },
      { item: "Truck" },
      { item: "Protege5" },
      { item: "Mazda5" },
      { item: "Mazda3" },
      { item: "Millenia" },
      { item: "B-Series Pickup" },
      { item: "Mazdaspeed 6" },
      { item: "Tribute Hybrid" },
      { item: "Mazdaspeed MX-5 Miata" },
      { item: "Mazdaspeed Protege" },
      { item: "929" },
      { item: "MX-6" },
      { item: "B-SERIES CAB PLUS" },
      { item: "323" },
      { item: "B4000" },
      { item: "MX-3" },
      { item: "Mazda6 Sport Wagon" },
      { item: "Miata" }
    ]
  },
  {
    make: "McLaren",
    model: [
      { item: "570S" },
      { item: "720S" },
      { item: "650S Spider" },
      { item: "MP4-12C" },
      { item: "570GT" },
      { item: "675LT Spider" },
      { item: "675LT Coupe" },
      { item: "650s" },
      { item: "MP4-12C Spider" },
      { item: "P12" },
      { item: "650S Coupe" },
      { item: "P1" },
      { item: "P11" }
    ]
  },
  {
    make: "Mercedes-Benz",
    model: [
      { item: "C-Class" },
      { item: "E-Class" },
      { item: "GLC" },
      { item: "S-Class" },
      { item: "GLS-Class" },
      { item: "GLA-Class" },
      { item: "CLA-Class" },
      { item: "Sprinter" },
      { item: "GLE-Class" },
      { item: "GLE" },
      { item: "M-Class" },
      { item: "GLC-Class" },
      { item: "GL-Class" },
      { item: "SL-Class" },
      { item: "Metris" },
      { item: "GLK-Class" },
      { item: "A-Class" },
      { item: "CLS-Class" },
      { item: "SLK-Class" },
      { item: "G-Class" },
      { item: "AMG GT" },
      { item: "CLS" },
      { item: "CLK-Class" },
      { item: "GLE-Class Coupe" },
      { item: "CL-Class" },
      { item: "GLE 350" },
      { item: "R-Class" },
      { item: "SLC-Class" },
      { item: "560" },
      { item: "SLS AMG" },
      { item: "GLC-Class Coupe" },
      { item: "300-Class" },
      { item: "380" },
      { item: "500-Class" },
      { item: "SLC - Class" },
      { item: "Sprinter Worker" },
      { item: "300" },
      { item: "B-Class" },
      { item: "B-Class Electric Drive" },
      { item: "Sprinter 3500" },
      { item: "Maybach" },
      { item: "420" },
      { item: "SLK" },
      { item: "SLS AMG GT" },
      { item: "SLS" },
      { item: "190-Class" },
      { item: "560-Class" },
      { item: "190" },
      { item: "400-Class" },
      { item: "C43 AMG" },
      { item: "Sprinter 2500" },
      { item: "420-Class" },
      { item: "SLR McLaren" },
      { item: "SLS AMG GT Final Edition" },
      { item: "ML55 AMG" },
      { item: "C36 AMG" },
      { item: "E55 AMG" },
      { item: "S" },
      { item: "240d" },
      { item: "260" },
      { item: "350-Class" },
      { item: "500 Series" },
      { item: "600-Class" },
      { item: "Sprinter Cargo" },
      { item: "190 Series" },
      { item: "190 Series 2.6" },
      { item: "500" },
      { item: "Sprinter 3500RV" }
    ]
  },
  {
    make: "Mercury",
    model: [
      { item: "Grand Marquis" },
      { item: "Mariner" },
      { item: "Milan" },
      { item: "Mountaineer" },
      { item: "Sable" },
      { item: "Montego" },
      { item: "Cougar" },
      { item: "Monterey" },
      { item: "Villager" },
      { item: "Mariner Hybrid" },
      { item: "Capri" },
      { item: "Mystique" },
      { item: "Marauder" },
      { item: "Milan Hybrid" },
      { item: "Tracer" },
      { item: "Sable Wagon" },
      { item: "Grand Marquis Wagon" },
      { item: "Marquis" },
      { item: "Topaz" }
    ]
  },
  {
    make: "MINI",
    model: [
      { item: "Cooper" },
      { item: "Cooper Countryman" },
      { item: "Cooper S Countryman" },
      { item: "Cooper S Clubman" },
      { item: "Cooper Clubman" },
      { item: "Clubman" },
      { item: "Roadster" },
      { item: "Cooper Convertible" },
      { item: "Countryman Plug-in Hybrid" },
      { item: "Countryman" },
      { item: "Hardtop 2 Door" },
      { item: "JCW Hardtop" },
      { item: "Cooper Paceman" },
      { item: "Hardtop 4 Door" },
      { item: "Cooper Coupe" },
      { item: "Cooper Roadster" },
      { item: "Convertible" },
      { item: "Hardtop" },
      { item: "JCW Convertible" },
      { item: "JCW Clubman" }
    ]
  },
  {
    make: "Mitsubishi",
    model: [
      { item: "Outlander" },
      { item: "Outlander Sport" },
      { item: "Mirage G4" },
      { item: "Mirage" },
      { item: "Eclipse Cross" },
      { item: "Lancer" },
      { item: "Outlander - PHEV" },
      { item: "Galant" },
      { item: "Eclipse" },
      { item: "Lancer Evolution" },
      { item: "Endeavor" },
      { item: "Eclipse Spyder" },
      { item: "Montero Sport" },
      { item: "Raider" },
      { item: "Montero" },
      { item: "Lancer Sportback" },
      { item: "3000GT" },
      { item: "Diamante" },
      { item: "i-MiEV" },
      { item: "Truck" },
      { item: "Lancer Rally Art" },
      { item: "Mighty Max Pickup" },
      { item: "Mighty Max" },
      { item: "RVR" }
    ]
  },
  {
    make: "Nissan",
    model: [
      { item: "Rogue" },
      { item: "Altima" },
      { item: "Sentra" },
      { item: "Frontier" },
      { item: "Murano" },
      { item: "Versa" },
      { item: "Titan" },
      { item: "Pathfinder" },
      { item: "Maxima" },
      { item: "Kicks" },
      { item: "Armada" },
      { item: "Rogue Sport" },
      { item: "Leaf" },
      { item: "NV" },
      { item: "NV200" },
      { item: "Versa Note" },
      { item: "NV Cargo" },
      { item: "Juke" },
      { item: "Rogue Sports" },
      { item: "Titan XD" },
      { item: "Xterra" },
      { item: "370Z" },
      { item: "Quest" },
      { item: "Rogue Select" },
      { item: "NV3500" },
      { item: "350Z" },
      { item: "NV Passenger" },
      { item: "Cube" },
      { item: "GT-R" },
      { item: "300ZX" },
      { item: "Altima Hybrid" },
      { item: "Murano CrossCabriolet" },
      { item: "Rogue Hybrid" },
      { item: "Pickup" },
      { item: "Truck" },
      { item: "Pathfinder (1999-5)" },
      { item: "240SX" },
      { item: "200SX" },
      { item: "UD1200" },
      { item: "NV2500 HD" },
      { item: "Ud1400" },
      { item: "Maxima Wagon" },
      { item: "Ud1800" },
      { item: "Ud3000" }
    ]
  },
  {
    make: "Oldsmobile",
    model: [
      { item: "Alero" },
      { item: "Bravada" },
      { item: "Intrigue" },
      { item: "Silhouette" },
      { item: "Aurora" },
      { item: "Cutlass Supreme" },
      { item: "Eighty Eight" },
      { item: "Eighty-Eight" },
      { item: "Cutlass" },
      { item: "Cutlass Ciera" },
      { item: "Toronado" },
      { item: "Ciera" },
      { item: "Ninety-Eight" },
      { item: "Royale" },
      { item: "Achieva" },
      { item: "Cutlass Calais" },
      { item: "Cutlass Salon" },
      { item: "Custom Cruiser" },
      { item: "Delta 88 Royale" },
      { item: "Ninety Eight" },
      { item: "LSS" },
      { item: "88" },
      { item: "Eighty-Eight Royale" },
      { item: "Hurst" },
      { item: "88 Delta Royale" },
      { item: "Calais" },
      { item: "Delta 88" }
    ]
  },
  { make: "Panoz", model: [{ item: "Esperante" }] },
  { make: "Peugeot", model: [{ item: "505" }] },
  {
    make: "Plymouth",
    model: [
      { item: "Prowler" },
      { item: "Grand Voyager" },
      { item: "Neon" },
      { item: "Voyager" },
      { item: "Breeze" },
      { item: "Acclaim" },
      { item: "Sundance" },
      { item: "Laser" }
    ]
  },
  {
    make: "Pontiac",
    model: [
      { item: "G6" },
      { item: "Grand Prix" },
      { item: "Vibe" },
      { item: "Grand Am" },
      { item: "Torrent" },
      { item: "Firebird" },
      { item: "Solstice" },
      { item: "G8" },
      { item: "G5" },
      { item: "Bonneville" },
      { item: "GTO" },
      { item: "Montana" },
      { item: "Sunfire" },
      { item: "Aztek" },
      { item: "Montana SV6" },
      { item: "Trans Am" },
      { item: "Fiero" },
      { item: "G3" },
      { item: "Sunbird" },
      { item: "Trans Sport" },
      { item: "Pursuit" },
      { item: "Parisienne" },
      { item: "6000" }
    ]
  },
  {
    make: "Porsche",
    model: [
      { item: "Macan" },
      { item: "Cayenne" },
      { item: "911" },
      { item: "Panamera" },
      { item: "718" },
      { item: "Boxster" },
      { item: "718 Cayman" },
      { item: "718 Boxster" },
      { item: "Cayman" },
      { item: "Cayman S" },
      { item: "944" },
      { item: "928" },
      { item: "968" },
      { item: "Carrera GT" },
      { item: "Cayenne Hybrid" },
      { item: "918 Spyder" },
      { item: "964" },
      { item: "993/911 Carrera 2" },
      { item: "924" },
      { item: "911 Carrera" }
    ]
  },
  {
    make: "RAM",
    model: [
      { item: "1500" },
      { item: "2500" },
      { item: "3500" },
      { item: "Laramie" },
      { item: "Promaster City" },
      { item: "Promaster Cargo Van" },
      { item: "ProMaster 2500" },
      { item: "ProMaster 1500" },
      { item: "ProMaster 3500" },
      { item: "5500" },
      { item: "5500HD" },
      { item: "4500HD" },
      { item: "4500" },
      { item: "Dakota" },
      { item: "2500 P" },
      { item: "CV Tradesman" },
      { item: "Ram Pickup 1500" },
      { item: "Promaster Window Van" },
      { item: "C/V Tradesman" },
      { item: "C/V Cargo Van" },
      { item: "ProMaster" },
      { item: "Ram Chassis 3500" },
      { item: "3500HD" },
      { item: "ProMaster 3500 Cutaway" },
      { item: "ProMaster 2500 Cutaway" },
      { item: "RAM TRUCK" },
      { item: "Ram Pickup 3500" }
    ]
  },
  { make: "Renault", model: [{ item: "ZOE" }] },
  {
    make: "Rolls-Royce",
    model: [
      { item: "Wraith" },
      { item: "Ghost" },
      { item: "Dawn" },
      { item: "Phantom" },
      { item: "Ghost Series II" },
      { item: "Phantom Drophead Coupe" },
      { item: "Cullinan" },
      { item: "Phantom Coupe" },
      { item: "Silver Spur" },
      { item: "Silver Seraph" },
      { item: "Corniche" },
      { item: "Silver Spirit" },
      { item: "Corniche II" },
      { item: "Park Ward" },
      { item: "Silver Dawn" }
    ]
  },
  {
    make: "Saab",
    model: [
      { item: "9-3" },
      { item: "9-5" },
      { item: "9-7X" },
      { item: "900" },
      { item: "9-2X" },
      { item: "9-4X" },
      { item: "9-5 Sportwagon" },
      { item: "9000" },
      { item: "9-3 SportCombi" }
    ]
  },
  {
    make: "Saturn",
    model: [
      { item: "VUE" },
      { item: "ION" },
      { item: "Aura" },
      { item: "Outlook" },
      { item: "S-Series" },
      { item: "Sky" },
      { item: "L-Series" },
      { item: "Astra" },
      { item: "Relay" },
      { item: "L300" },
      { item: "SL" },
      { item: "VUE Hybrid" },
      { item: "LS" },
      { item: "SW" },
      { item: "SC" },
      { item: "Aura Hybrid" },
      { item: "LW" }
    ]
  },
  {
    make: "Scion",
    model: [
      { item: "tC" },
      { item: "xB" },
      { item: "iM" },
      { item: "FR-S" },
      { item: "iA" },
      { item: "xD" },
      { item: "xA" },
      { item: "iQ" }
    ]
  },
  { make: "Smart", model: [{ item: "Fortwo" }] },
  {
    make: "Sterling",
    model: [
      { item: "Acterra" },
      { item: "L7500" },
      { item: "L8500" },
      { item: "Lt9500" },
      { item: "360" },
      { item: "At9500" },
      { item: "Bullet" },
      { item: "Sc8000" },
      { item: "Lt8500" },
      { item: "M6500" },
      { item: "M7500" },
      { item: "827" },
      { item: "A9500" },
      { item: "Actera" },
      { item: "L7501" },
      { item: "L8513" },
      { item: "L9500" },
      { item: "L9501" },
      { item: "L9511" },
      { item: "Lt8511" },
      { item: "M5500 Acterra" },
      { item: "M7500 Actera" },
      { item: "Sc8000 Cargo" }
    ]
  },
  {
    make: "Subaru",
    model: [
      { item: "Outback" },
      { item: "Forester" },
      { item: "Impreza" },
      { item: "Crosstrek" },
      { item: "Legacy" },
      { item: "Ascent" },
      { item: "WRX" },
      { item: "XV Crosstrek" },
      { item: "BRZ" },
      { item: "Impreza WRX" },
      { item: "Tribeca" },
      { item: "B9 Tribeca" },
      { item: "Baja" },
      { item: "Legacy Wagon" },
      { item: "SVX" },
      { item: "GL Wagon" }
    ]
  },
  {
    make: "Suzuki",
    model: [
      { item: "SX4" },
      { item: "Grand Vitara" },
      { item: "Forenza" },
      { item: "XL7" },
      { item: "XL-7" },
      { item: "Kizashi" },
      { item: "VL800" },
      { item: "Equator" },
      { item: "Reno" },
      { item: "Aerio" },
      { item: "GSX1300R" },
      { item: "GSX-R600" },
      { item: "GSX-R1000" },
      { item: "GSX-R750L1" },
      { item: "Verona" },
      { item: "VZ800" },
      { item: "VL1500" },
      { item: "VZR1800" },
      { item: "Vitara" },
      { item: "AN650" },
      { item: "Esteem" },
      { item: "GSX-R600L1" },
      { item: "GSX600F" },
      { item: "LS650" },
      { item: "Samurai" },
      { item: "Sidekick" },
      { item: "VS1400" },
      { item: "VS800" },
      { item: "GZ250" },
      { item: "SFV650" },
      { item: "DL1000" },
      { item: "GSX-R750" },
      { item: "SX4 Sport" },
      { item: "AN400" },
      { item: "DL650" },
      { item: "Dl650al" },
      { item: "GSX750F" },
      { item: "Gsx-S750zl/Gsx-S750l" },
      { item: "Dr-Z400sm" },
      { item: "Gsx-R750l7" },
      { item: "Kingquad" },
      { item: "LT-Z400" },
      { item: "Lt-F250" },
      { item: "RM-Z450" },
      { item: "VZ1500" },
      { item: "GS500E" },
      { item: "GSX-R 1300" },
      { item: "GSX250RL8" },
      { item: "Gsx-R1000l7/Gsx-R1000al7" },
      { item: "Gsx-S1000fa" },
      { item: "Gsx1300ral" },
      { item: "Gsx1300ral/Gsx1300razl" },
      { item: "Lt-A750" },
      { item: "SV650" },
      { item: "Sv650l7" },
      { item: "Swift" },
      { item: "Tu250x" },
      { item: "VLR1800" },
      { item: "250 GT Naked" },
      { item: "An400al" },
      { item: "DR650SE" },
      { item: "Dl1000al/Dl1000aal" },
      { item: "Dl650aal/Dl650al" },
      { item: "Dr-Z400s" },
      { item: "Esteem Wagon" },
      { item: "GSX-R1100" },
      { item: "GSX650F" },
      { item: "Gsf1200" },
      { item: "Gsf1250s" },
      { item: "Gsf1250sa" },
      { item: "Gsf1250sa/Gsx1250sa" },
      { item: "Gsf600s" },
      { item: "Gsx-S1000fal8" },
      { item: "Gv250" },
      { item: "LT-A400" },
      { item: "LT-A400FCL/LT-A400FL/LT-A400FZL (KingQuad 400 ASi)" },
      {
        item:
          "LT-A750XPCL/LT-A750XPL/LT-A750XPZL (KingQuad 750 AXi Pwr Strg)/Ltd Edition"
      },
      { item: "Lt-F160" },
      { item: "Lt-F400" },
      { item: "Lt-F4wdxs" },
      { item: "Lt-F500f" },
      { item: "M 50" },
      { item: "RF900R" },
      { item: "Sv1000" },
      { item: "Tl1000r" },
      { item: "Uh200l" },
      { item: "Unknown" },
      { item: "VSTROM" },
      { item: "Vl1500l/Vl1500bl/Vl1500tl/vl1500btl" },
      { item: "X-90" }
    ]
  },
  {
    make: "Tesla",
    model: [
      { item: "Model S" },
      { item: "Model X" },
      { item: "Model 3" },
      { item: "Roadster" }
    ]
  },
  {
    make: "Toyota",
    model: [
      { item: "Camry" },
      { item: "Corolla" },
      { item: "RAV4" },
      { item: "Highlander" },
      { item: "Tacoma" },
      { item: "Tundra" },
      { item: "Sienna" },
      { item: "4-Runner" },
      { item: "Avalon" },
      { item: "4Runner" },
      { item: "Prius" },
      { item: "Yaris" },
      { item: "C-HR" },
      { item: "Camry Hybrid" },
      { item: "Sequoia" },
      { item: "Prius Prime" },
      { item: "Prius c" },
      { item: "86" },
      { item: "Venza" },
      { item: "FJ Cruiser" },
      { item: "RAV4 Hybrid" },
      { item: "Land Cruiser" },
      { item: "Prius V" },
      { item: "Yaris iA" },
      { item: "Camry Solara" },
      { item: "Matrix" },
      { item: "Highlander Hybrid" },
      { item: "Avalon Hybrid" },
      { item: "Corolla iM" },
      { item: "Prius Plug-in" },
      { item: "Celica" },
      { item: "Mirai" },
      { item: "MR2 Spyder" },
      { item: "ECHO" },
      { item: "Pickup" },
      { item: "Supra" },
      { item: "T100" },
      { item: "Tercel" },
      { item: "MR2" },
      { item: "RAV4 EV" },
      { item: "Previa" },
      { item: "Cressida" },
      { item: "Paseo" },
      { item: "Solara" },
      { item: "Camry Wagon" },
      { item: "CORROLA" },
      { item: "Corolla Wagon" },
      { item: "Tercel Wagon" },
      { item: "Van" }
    ]
  },
  {
    make: "Volkswagen",
    model: [
      { item: "Jetta" },
      { item: "Tiguan" },
      { item: "Atlas" },
      { item: "Passat" },
      { item: "Beetle" },
      { item: "Jetta SportWagen" },
      { item: "Golf" },
      { item: "CC" },
      { item: "Golf Alltrack" },
      { item: "Golf GTI" },
      { item: "Golf SportWagen" },
      { item: "Touareg" },
      { item: "GTI" },
      { item: "Beetle Convertible" },
      { item: "Eos" },
      { item: "Tiguan Limited" },
      { item: "e-Golf" },
      { item: "Routan" },
      { item: "Golf R" },
      { item: "Rabbit" },
      { item: "New Beetle" },
      { item: "Jetta GLI" },
      { item: "Touareg 2" },
      { item: "Jetta Hybrid" },
      { item: "GLI" },
      { item: "Cabrio" },
      { item: "R32" },
      { item: "Eurovan" },
      { item: "Phaeton" },
      { item: "Vanagon" },
      { item: "Passat Wagon" },
      { item: "Corrado" },
      { item: "Cabriolet" },
      { item: "Fox" },
      { item: "Scirocco" }
    ]
  },
  {
    make: "Volvo",
    model: [
      { item: "XC90" },
      { item: "XC60" },
      { item: "S60" },
      { item: "S90" },
      { item: "V60 Cross Country" },
      { item: "XC70" },
      { item: "V60" },
      { item: "S80" },
      { item: "S40" },
      { item: "C70" },
      { item: "XC40" },
      { item: "V90" },
      { item: "V90 Cross Country" },
      { item: "V70" },
      { item: "C30" },
      { item: "V50" },
      { item: "S60 Cross Country" },
      { item: "S70" },
      { item: "VNL" },
      { item: "XC" },
      { item: "850" },
      { item: "XC90 Hybrid" },
      { item: "V40" },
      { item: "240" },
      { item: "960" },
      { item: "740" },
      { item: "940" },
      { item: "VNL670" },
      { item: "960 Wagon" },
      { item: "VHD" },
      { item: "VNM" },
      { item: "760" },
      { item: "VND" },
      { item: "WG" }
    ]
  }
];
